### PR TITLE
Fix E2E testing for github actions

### PR DESCRIPTION
**Pull request by the-redback**
Follow up PR of: https://github.com/kubedb/postgres/pull/292

- [x] Run E2e tests of stash integretion on github actions
- [x] Fix few e2e tests to run on parallel
- [x] Increase db version. xref: https://github.com/kubedb/postgres/pull/292
- [x] Updated wal-g version
- [x] Do not skip logs of pg_ctl and other commands in postgres docker (ie, ` > /dev/null`)
- [x] Convert `gitrepo` volumes to `configmap` in initialization testing
- [x] Fix linter errors
- [x] Use stash 0.9.0-rc.2

### CODE REVIEW

**Comment by tamalsaha** [comment]
Where is the port forwarding thing happening?

```
[2] E1015 22:45:58.321967    4191 portforward.go:400] an error occurred forwarding 44869 -> 5432: error forwarding port 5432 to pod 455dc2e0fae0ea13103d63ecafef7b0fa7335658b85f69537e26eb72bd903613, uid : failed to execute portforward in network namespace "/var/run/netns/cni-39e75f2b-2a7b-6dff-8bd5-9f9674e4dac4": socat command returns error: exit status 1, stderr: "2019/10/15 22:45:58 socat[2088] E connect(5, AF=2 127.0.0.1:5432, 16): Connection refused\n"
```

**Comment by tamalsaha** [comment]
Port forwarding seem to work in isolation https://github.com/tamalsaha/kind-port-forward-action-demo

**Comment by the-redback** [comment]
> Where is the port forwarding thing happening?
> 
> `[2] E1015 22:45:58.321967 4191 portforward.go:400] an error occurred forwarding 44869 -> 5432: error forwarding port 5432 to pod 455dc2e0fae0ea13103d63ecafef7b0fa7335658b85f69537e26eb72bd903613, uid : failed to execute portforward in network namespace "/var/run/netns/cni-39e75f2b-2a7b-6dff-8bd5-9f9674e4dac4": socat command returns error: exit status 1, stderr: "2019/10/15 22:45:58 socat[2088] E connect(5, AF=2 127.0.0.1:5432, 16): Connection refused\n"`

This is happening because the Postgres container is not accepting any traffic on 5432 port, but as the Postgres CRD object's status is `running`, e2e tests are trying to establish the connection with db. 
Eventually, the connection will be successful after couple of retries.
To overcome this scenario, we have to add `readiness` probe to the pods.

**Comment by the-redback** [comment]
Archiving with local PVC is still failing. It is already tracked in this issue: https://github.com/kubedb/project/issues/623 
We can take a look at that part later, I guess.

**Pull request merged**
