### PR TITLE
use POSTGRES_USER as replication user (kubedb#661)

### PR DESCRIPTION
**Pull request by ghao1**

### CODE REVIEW

**Comment by donicrosby** [comment]
Likely there is not going to need to be a change to the user, this is more secure because it assumes the postgres user:
```
...
host  replication postgres    0.0.0.0/0       md5
host  all         all         0.0.0.0/0       md5
```

**Comment by ghao1** [comment]
Allow me to explain the case here. In our kubedb postgres manifest, we use spec.databaseSecret.secretName to specify a secret which contains superuser name for postgres database as POSTGRES_USER key and password as POSTGRES_PASSWORD key, following the example at https://kubedb.com/docs/0.9.0/guides/postgres/quickstart/quickstart/

In that secret, We make the superuser has a custom user name (for demo purpose, let's say it is a user called **kdbadmin**). When db instances are created, **kdbadmin** is set up as a supseruser account; user postgres is disabled for login, and its password is empty. 

Now the slave instances all have env variable POSTGRES_PASSWORD set to **kdbadmin's** password; as a result, slaves try to connect to master instance as user postgres with kdbadmin's password, as you can see the connection attempts can never succeed.

So if you think it is better to have postgres user dedicated for replication, could you provide a way to 

1. setup user postgres with a hardened password as part of kubedb postgres bringup; and

1. make slave use user postgres's password to connect to master.

Thanks!

**Comment by the-redback** [comment]
Hello,

We have moved our docker files for postgres to https://github.com/kubedb/postgres-docker. 
Can you please move your changes and open a PR there?

Thanks.

**Comment by ghao1** [comment]
certainly.

**Pull request closed without merging**
